apiVersion: apps/v1
kind: Deployment
metadata:
  name:  node-cache-deployment
  labels:
    name:  node-cache-app
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  web
    spec:
      containers:
      - name: node-cache
        image: gcr.io/kr-practice-e2e/node-cache-api:latest
        ports:
        - containerPort: 3000
      - name: cache-with-redis
        image:  redis:latest
      restartPolicy: Always
      imagePullPolicy: Always