apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodecache-web-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: node-cache
        image: gcr.io/kr-practice-e2e/node-cache-api:latest
        ports:
        - containerPort: 3000
      - name: cache-with-redis
        image:  redis:latest
        ports:
        - containerPort: 6379